name: Deploy to hosting provider

on:
  push:
    tags:
      - "v*"

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ARTIFACT: me-ancliz-website

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Tag
        id: set_tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "TAG=${TAG}" >> $GITHUB_OUTPUT
          echo "VERSION=${TAG}" >> $GITHUB_ENV

      - name: Zip
        run: |
          zip -r "${{ env.PROJECT_ARTIFACT }}-${{steps.set_tag.outputs.TAG}}.zip" . -x ".*" -x "target/"
          echo v $VERSION
          echo artifact $PROJECT_ARTIFACT
          ls

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_ARTIFACT }}-${{steps.set_tag.outputs.TAG}}
          path: ${{ env.PROJECT_ARTIFACT }}-${{steps.set_tag.outputs.TAG}}.zip
    
      - name: Get artifact download URL
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_KEY}}    
          ARTIFACT_NAME: ${{ env.PROJECT_ARTIFACT }}-${{ steps.set_tag.outputs.TAG }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
        run: |
          ARTIFACT_ID=$(curl -s -H "Authorization: token $DEPLOY_TOKEN" \
            "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID/artifacts" | \
            jq -r ".artifacts[] | select(.name==\"$ARTIFACT_NAME\") | .id")

          if [[ -z "$ARTIFACT_ID" ]]; then
            echo "Artifact not found"
            exit 1
          fi

          DOWNLOAD_URL="https://api.github.com/repos/$REPO/actions/artifacts/$ARTIFACT_ID/zip"
          echo "📦 Artifact download URL:"
          echo "$DOWNLOAD_URL"

      - name: SSH and run deploy
        uses: appleboy/ssh-action@v1.0.3
        env:
          REPO: ${{ github.repository }}
          VERSION: ${{ steps.set_tag.outputs.TAG }}
          RUN_ID: ${{ github.run_id }}
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.HOST_PRIVATE_KEY }}
          script: ./deploy.sh ${{ env.REPO }} ${{ env.PROJECT_ARTIFACT }}-${{ env.VERSION }} ${{ env.RUN_ID }}
