name: Deploy to hosting provider

on:
  push:
    tags:
      - "v*"

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ARTIFACT: me-ancliz-website

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Tag
        id: set_tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "TAG=${TAG}" >> $GITHUB_OUTPUT
          echo "TAG_REPLACED=${TAG//./_}" >> $GITHUB_OUTPUT
          echo "VERSION=${TAG}" >> $GITHUB_ENV
          echo "VERSION_REPLACED=${TAG//./_}" >> $GITHUB_ENV

      - name: Zip
        run: |
          zip -r "${{ env.PROJECT_ARTIFACT }}-${{steps.set_tag.outputs.TAG_REPLACED}}.zip" . -x ".*" -x "target/"
          echo v $VERSION_REPLACED
          echo artifact $PROJECT_ARTIFACT
          ls

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_ARTIFACT }}-${{steps.set_tag.outputs.TAG_REPLACED}}
          path: ${{ env.PROJECT_ARTIFACT }}-${{steps.set_tag.outputs.TAG_REPLACED}}.zip
    
      - name: SCP zip to server
        uses: appleboy/scp-action@v0.1.7
        env:
          VERSION: ${{ steps.set_tag.outputs.TAG_REPLACED }}
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.HOST_PRIVATE_KEY }}
          source: ${{ env.PROJECT_ARTIFACT }}-${{ env.VERSION }}.zip
          target: "/home/${{ secrets.HOST }}/versions/${{ env.VERSION }}"
      
      - name: SSH and run deploy
        uses: appleboy/ssh-action@v1.0.3
        env:
          VERSION: ${{ steps.set_tag.outputs.TAG_REPLACED }}
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.HOST_PRIVATE_KEY }}
          script: ./deploy -f ${{ env.PROJECT_ARTIFACT }}-${{ env.VERSION }}.zip